name: Tests

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-build.txt
        python -m pip install -r requirements-tests.txt
        #conda install -c conda-forge ndindex
        python -m pip install -r requirements-runtime.txt
        python -vv -c "import ndindex"

    - name: Build
      run: |
        python setup.py build_ext --inplace
    - name: Test
      run: |
        python -m pytest
